#mariadb, phypmyadmin and car-db
version: '3.9'                       

services:
   db:
      image: mariadb:latest
      container_name: mariadb165
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: 1234
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: default_schema
      volumes:
        - ./initcar.sql:/docker-entrypoint-initdb.d/1.sql       
      ports:
       - '3307:3306'
       
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin165
      ports:
       - '80:80'
      environment:
        PMA_HOST: db
        
volumes:
    dbdata: